name: Build Example Project
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build_example_project.yml'
      - 'Example/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app
jobs:
  build:
    name: Build example project for iPhone 15
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          xcodebuild build\
            -project Example/Example.xcodeproj\
            -scheme Example\
            -sdk iphonesimulator\
            -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0"
